# Generated by Django 3.2.8 on 2022-01-22 16:17

from django.db import migrations, models
import django.forms.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateField(null=True, verbose_name=django.forms.fields.DateTimeField),
        ),
    ]
