# Generated by Django 3.2.8 on 2022-01-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='username',
        ),
    ]
