# Generated by Django 3.2.8 on 2022-01-25 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_client_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='username',
            new_name='name',
        ),
    ]
